SFDC=* NOT SFDC IN ("DC13", "DC25")
splunk_server_group = *_indexers 
(host="*" OR servername="*")
index=hcm_sac_app
(sourcetype = app_log_sac)
sac_app_log_level = ERROR

| rex field=_raw "^.*?\]\s([a-z][\.])*(?<component>.*?)\s+:\s\["
| rex field=_raw "^(?<skip>(?:[^\]\n]*\]){3})\s*(?P<err_message>.+)" 

| eval err_message=case(
    like(err_message,"[129]: transaction rolled back by an internal error: Allocation failed%"),"[129]: transaction rolled back by an internal error: Allocation failed",
    like(err_message,"%Cannot rollback transaction%"),"Cannot rollback transaction",
    like(err_message,"%Connection to database server lost%"),"Connection to database server lost",
    like(err_message,"%Error during processSynchronization%"),"Error during processSynchronization",
    like(err_message,"%Error executing SQL%PooledConnection has already been closed%"),"Error executing SQL...PooledConnection has already been closed",
    like(err_message,"%Error node is not null"),"Error node is not null",
    like(err_message,"%ERROR_CODE 6006 Error while injecting%"),"ERROR_CODE 6006 Error while injecting",
    like(err_message,"%Exception while processing variables"),"Exception while processing variables",
    like(err_message,"%Failed to get the server information%"),"Failed to get the server information",
    like(err_message,"%java.sql.SQLException: PooledConnection has already been closed%"),"PooledConnection has already been closed",
    like(err_message,"%liquibase.exception.DatabaseException: java.sql.SQLException: PooledConnection has already been closed%"),"PooledConnection has already been closed",
    like(err_message,"%liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: PooledConnection has already been closed%"),"PooledConnection has already been closed",
    like(err_message,"%Query definition missing%"),"Query definition missing",
    like(err_message,"%RTEException: Connection to database server lost%error 104 - Connection reset"),"RTEException: Connection to database server lost...error 104 - Connection reset",
    like(err_message,"%IOException: error 104 - Connection reset by peer"),"IOException: error 104 - Connection reset by peer",
    like(err_message,"%Unhandled error in servlet filter processing%"),"Unhandled error in servlet filter processing",
    like(err_message,"403 Forbidden%"),"403 Forbidden",
    like(err_message,"406 Not Acceptable%"),"406 Not Acceptable",
    like(err_message,"500 Internal Server Error%"),"500 Internal Server Error",
    like(err_message,"502 Bad Gateway%"),"502 Bad Gateway",
    like(err_message,"502%the server%received an invalid response%"),"502 the server received an invalid response",
    like(err_message,"Access to the object%is not allowed."),"Access to the object is not allowed.",
    like(err_message,"Application exception overridden by rollback exception%"),"Application exception overridden by rollback exception",
    like(err_message,"Application run failed%"),"Application run failed",
    like(err_message,"Bad server response%"),"Bad server response",
    like(err_message,"Calc view recovery is not support for this query type%"),"Calc view recovery is not support for this query type",
    like(err_message,"Calculation view not active%"),"Calculation view not active",
    like(err_message,"Call to read audit log failed%"),"Call to read audit log failed",
    like(err_message,"Cannot forward to error page for request%"),"Cannot forward to error page for request",
    like(err_message,"Cannot get database name%"),"Cannot get database name",
    like(err_message,"Cannot rollback transaction%"),"Cannot rollback transaction",
    like(err_message,"com.sap.db.jdbc.exceptions.RTEException: Connection to database server lost; check server and network status [System error: java.io.IOException: error 104 - Connection reset by peer]"),"IOException: error 104 - Connection reset by peer",
    like(err_message,"Connection to database server lost; check server and network status [System error: java.io.IOException: error 104 - Connection reset by peer]"),"IOException: error 104 - Connection reset by peer",
    like(err_message,"Connection to database server lost%"),"Connection to database server lost",
    like(err_message,"Context field%for GDPR audit logging not provided%"),"Context field for GDPR audit logging not provided",
    like(err_message,"Data source field list doesn't have the field%"),"Data source field list doesn't have the field",
    like(err_message,"Error : "),"Error :",
    like(err_message,"%The parallel execution limit per tenant has been exceeded%"),"The parallel execution limit per tenant has been exceeded",
    like(err_message,"ERROR 4501 Validation end point timed out%"),"ERROR 4501 Validation end point timed out",
    like(err_message,"ERROR 4502 Response of external server cannot be parsed%"),"ERROR 4502 Response of external server cannot be parsed",
    like(err_message,"ERROR 4505 Query Builder Validation Internal Server error on the LoB end point side%"),"ERROR 4505 Query Builder Validation Internal Server error on the LoB end point side",
    like(err_message,"Error Code : 3108 Cannot get user authentication information%"),"Error Code : 3108 Cannot get user authentication information",
    like(err_message,"Error Code : 3111 Token decryption failed"),"Error Code : 3111 Token decryption failed",
    like(err_message,"Error Code : 4521 Not authorized to request metadata"),"Error Code : 4521 Not authorized to request metadata",
    like(err_message,"ERROR CODE%missing GDPR context field"),"ERROR CODE : missing GDPR context field",
    like(err_message,"Error creating DB connection%"),"Error creating DB connection",
    like(err_message,"Error during processSynchronization%"),"Error during processSynchronization",
    like(err_message,"Error executing SQL%"),"Error executing SQL",
    like(err_message,"Error%Query has error while exporting"),"Query has error while exporting",
    like(err_message,"Error from HanaFileAPI%Error while writing file%"),"Error while writing file",
    like(err_message,"Error in GenericRemoteAPI: GET%"),"Error in GenericRemoteAPI: GET",
    like(err_message,"Error in GenericRemoteAPI: POST%"),"Error in GenericRemoteAPI: POST",
    like(err_message,"Error in Request Processing: Error while writing file"),"Error in Request Processing: Error while writing file",
    like(err_message,"Error node is not null"),"Error node is not null",
    like(err_message,"Error occured while extracting story execution details%"),"Error occured while extracting story execution details",
    like(err_message,"Error while writing csv export response to DB"),"Error while writing csv export response to DB",
    like(err_message,"ERROR_CODE 3512 Exception on creating dataSource"),"ERROR_CODE 3512 Exception on creating dataSource",
    like(err_message,"ERROR_CODE 3516 Cannot find dbPoolId in ServerConfiguration"),"ERROR_CODE 3516 Cannot find dbPoolId in ServerConfiguration",
    like(err_message,"ERROR_CODE 3518 Cannot get DB Connection from DataSource%"),"ERROR_CODE 3518 Cannot get DB Connection from DataSource",
    like(err_message,"ERROR_CODE 42010 Unsupported operation%"),"ERROR_CODE 42010 Unsupported operation",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000002: Allocation failed%"),"ERROR_CODE 42014 Caught exception : exception 1000002: Allocation failed",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000013%"),"ERROR_CODE 42014 Caught exception : exception 1000013: failed to execute all requests ",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 1000087%"),"ERROR_CODE 42014 Caught exception : exception 1000087: basic_ios::clear",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42012%"),"ERROR_CODE 42014 Caught exception : exception 42012: The wrong value type was requested",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42018%"),"ERROR_CODE 42014 Caught exception : exception 42018: Internal error occurred while processing",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42111%"),"ERROR_CODE 42014 Caught exception : exception 42111: SQL Error",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42129%"),"ERROR_CODE 42014 Caught exception : exception 42129: Data failed to persist successfully",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42208%"),"ERROR_CODE 42014 Caught exception : exception 42208: Can't read the view",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42218%"),"ERROR_CODE 42014 Caught exception : exception 42218: The Blending mapping is wrongly defined",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42223%"),"ERROR_CODE 42014 Caught exception : exception 42223: Blending failed due to internal error",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42422%"),"ERROR_CODE 42014 Caught exception : exception 42422: The operation in the formula operator is invalid",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42432%"),"ERROR_CODE 42014 Caught exception : exception 42432: Dimension attribute referenced in view is not defined",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42445%"),"ERROR_CODE 42014 Caught exception : exception 42445: A field name in a filter must be a view column or dimension",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42492%"),"ERROR_CODE 42014 Caught exception : exception 42492: The column names are empty",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42556%"),"ERROR_CODE 42014 Caught exception : exception 42556: Extended dimension processing error",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42567%"),"ERROR_CODE 42014 Caught exception : exception 42567: Error during formula evaluation",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000002%"),"ERROR_CODE 42014 Caught exception : exception 70000002: general error",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000004%"),"ERROR_CODE 42014 Caught exception : exception 70000004: cannot allocate enough memory",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000009%"),"ERROR_CODE 42014 Caught exception : exception 70000009: Memory allocation failed",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000022%"),"ERROR_CODE 42014 Caught exception : exception 70000022: statement recompile required",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000258%"),"ERROR_CODE 42014 Caught exception : exception 70000258: insufficient privilege",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000259: invalid table name%"),"ERROR_CODE 42014 Caught exception : exception 70000259: invalid table name",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000260: invalid column name%"),"ERROR_CODE 42014 Caught exception : exception 70000260: invalid column name",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000264: invalid datatype%"),"ERROR_CODE 42014 Caught exception : exception 70000264: invalid datatype",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000303: invalid DATE, TIME or TIMESTAMP value%"),"ERROR_CODE 42014 Caught exception : exception 70000303: invalid DATE, TIME or TIMESTAMP value",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000304: division by zero undefined%"),"ERROR_CODE 42014 Caught exception : exception 70000304: division by zero undefined",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000314: numeric overflow%"),"ERROR_CODE 42014 Caught exception : exception 70000314: numeric overflow",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000339: invalid number%"),"ERROR_CODE 42014 Caught exception : exception 70000339: invalid number",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70000391: invalidated view%"),"ERROR_CODE 42014 Caught exception : exception 70000391: invalidated view",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70002048: column store error%"),"ERROR_CODE 42014 Caught exception : exception 70002048: column store error",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70002620: executor%"),"ERROR_CODE 42014 Caught exception : exception 70002620: executor",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 70034051: Error during plan execution%"),"ERROR_CODE 42014 Caught exception : exception 70034051: Error during plan execution",
    like(err_message,"ERROR_CODE 42100 The DataSource is invalid%"),"ERROR_CODE 42100 The DataSource is invalid",
    like(err_message,"ERROR_CODE 42111 SQL Error%"),"ERROR_CODE 42111 SQL Error",
    like(err_message,"ERROR_CODE 42129 Data failed to persist successfully%"),"ERROR_CODE 42129 Data failed to persist successfully",
    like(err_message,"ERROR_CODE 42201 Column not found%"),"ERROR_CODE 42201 Column not found",
    like(err_message,"ERROR_CODE 42208 Can't read the view%"),"ERROR_CODE 42208 Can't read the view",
    like(err_message,"ERROR_CODE 42218 The Blending mapping is wrongly defined%"),"ERROR_CODE 42218 The Blending mapping is wrongly defined",
    like(err_message,"ERROR_CODE 42227 One of the blending source queries returned an empty result%"),"ERROR_CODE 42227 One of the blending source queries returned an empty result",
    like(err_message,"ERROR_CODE 42420 The aggregation type is invalid%"),"ERROR_CODE 42420 The aggregation type is invalid",
    like(err_message,"ERROR_CODE 42473 A non-empty value must be used in the comparison"),"ERROR_CODE 42473 A non-empty value must be used in the comparison",
    like(err_message,"ERROR_CODE 42474 The view doesn't contain the measure%"),"ERROR_CODE 42474 The view doesn't contain the measure",
    like(err_message,"ERROR_CODE 42494 CustomDimension%must have one measure only"),"ERROR_CODE 42494 CustomDimension must have one measure only",
    like(err_message,"ERROR_CODE 42515 The aggregation type is not allowed for the data type of the measure%"),"ERROR_CODE 42515 The aggregation type is not allowed for the data type of the measure",
    like(err_message,"ERROR_CODE 42518 Inconsistent state%"),"ERROR_CODE 42518 Inconsistent state",
    like(err_message,"ERROR_CODE 42556 Extended dimension processing error%"),"ERROR_CODE 42556 Extended dimension processing error",
    like(err_message,"ERROR_CODE 42560 Invalid default aggregation type used%"),"ERROR_CODE 42560 Invalid default aggregation type used",
    like(err_message,"ERROR_CODE 42561 At least one exception aggregation dimension must be used%"),"ERROR_CODE 42561 At least one exception aggregation dimension must be used",
    like(err_message,"ERROR_CODE 42581 Invalid sort definition%"),"ERROR_CODE 42581 Invalid sort definition",
    like(err_message,"ERROR_CODE 42709 The selection returned more records than the limit in MaxResultRecords%"),"ERROR_CODE 42709 The selection returned more records than the limit in MaxResultRecords",
    like(err_message,"ERROR_CODE 4531 Failed to get metadata from LOB service%"),"ERROR_CODE 4531 Failed to get metadata from LOB service",
    like(err_message,"ERROR_CODE 4537 Cannot get tenant connection details%"),"ERROR_CODE 4537 Cannot get tenant connection details",
    like(err_message,"ERROR_CODE 4544 Server error in Read audit log request%"),"ERROR_CODE 4544 Server error in Read audit log request",
    like(err_message,"ERROR_CODE 4545 Metadata Server Error%"),"ERROR_CODE 4545 Metadata Server Error",
    like(err_message,"ERROR_CODE 4546 Forbidden Metadata Response Error%"),"ERROR_CODE 4546 Forbidden Metadata Response Error",
    like(err_message,"ERROR_CODE 4555 Writing to audit log failed%"),"ERROR_CODE 4555 Writing to audit log failed",
    like(err_message,"ERROR_CODE 4558 Error creating DB connection%"),"ERROR_CODE 4558 Error creating DB connection",
    like(err_message,"ERROR_CODE 4562 v2/preexecutionmetadata response%"),"ERROR_CODE 4562 v2/preexecutionmetadata response failed",
    like(err_message,"ERROR_CODE 6002 We failed to execute the query%"),"ERROR_CODE 6002 We failed to execute the query",
    like(err_message,"ERROR_CODE 6006 Error while injecting%"),"ERROR_CODE 6006 Error while injecting",
    like(err_message,"ERROR_CODE 6009 Unsupported dimension name in the query%"),"ERROR_CODE 6009 Unsupported dimension name in the query",
    like(err_message,"ERROR_CODE 6013 We found an unsupported query type%"),"ERROR_CODE 6013 We found an unsupported query type",
    like(err_message,"ERROR_CODE 6016 We found an error while executing the SQL statement%"),"ERROR_CODE 6016 We found an error while executing the SQL statement",
    like(err_message,"ERROR_CODE5037\"Column does not exist in calculation View\"%"),"ERROR_CODE5037\"Column does not exist in calculation View\"",
    like(err_message,"ERROR_CODE5040 Query is not activated and will be deleted%"),"ERROR_CODE5040 Query is not activated and will be deleted",
    like(err_message,"ERROR_CODE5041 Query is not activated and will be reverted%"),"ERROR_CODE5041 Query is not activated and will be reverted",
    like(err_message,"ERROR-5016 Source Field%does not exists%"),"ERROR-5016 Source Field does not exists",
    like(err_message,"ERROR-5028 Right datasource%is used in two joins"),"ERROR-5028 Right datasource is used in two joins",
    like(err_message,"ERROR-5031 OutputField%not exists"),"ERROR-5031 OutputField not exists",
    like(err_message,"ERROR-6002: LogicalModelName is null/empty%"),"ERROR-6002: LogicalModelName is null/empty",
    like(err_message,"Exception while getting DBPool"),"Exception while getting DBPool",
    like(err_message,"Exception while processing variables"),"Exception while processing variables",
    like(err_message,"Export failed as variables definition is missing or invalid%"),"Export failed as variables definition is missing or invalid",
    like(err_message,"Fail to create%object%"),"Fail to create object",
    like(err_message,"Failed to get the server information%"),"Failed to get the server information",
    like(err_message,"Failed to update job status%"),"Failed to update job status",
    like(err_message,"Forwarding to error page from request%"),"Forwarding to error page from request",
    like(err_message,"Getting secrets from vault failed during initial load"),"Getting secrets from vault failed during initial load",
    like(err_message,"%NullPointerException: while trying to invoke the method%"),"NullPointerException: while trying to invoke the method",
    like(err_message,"%RuntimeException: Cannot end scope%"),"RuntimeException: Cannot end scope",
    like(err_message,"%SQLException: Connection has already been closed%"),"SQLException: Connection has already been closed",
    like(err_message,"%SQLException: PooledConnection has already been closed%"),"SQLException: PooledConnection has already been closed",
    like(err_message,"%JDBCDriverException%cannot allocate enough memory%"),"JDBCDriverException: cannot allocate enough memory",
    like(err_message,"%DatabaseException: Error executing SQL%"),"DatabaseException: Error executing SQL",
    like(err_message,"%SQLException: PooledConnection has already been closed%"),"SQLException: PooledConnection has already been closed",
    like(err_message,"%JDBCDriverException%cannot allocate enough memory%"),"JDBCDriverException: cannot allocate enough memory",
    like(err_message,"%SQLException: PooledConnection has already been closed%"),"SQLException: PooledConnection has already been closed ",
    like(err_message,"%SQLException: PooledConnection has already been closed%"),"SQLException: PooledConnection has already been closed",
    like(err_message,"Metadata missing for object%"),"Metadata missing for object",
    like(err_message,"Migration failed for query%"),"Migration failed for query",
    like(err_message,"No matching output column found%"),"No matching output column found",
    like(err_message,"Node list not valid%"),"Node list not valid",
    like(err_message,"PackageName%does not have the correct naming convention%"),"PackageName does not have the correct naming convention",
    like(err_message,"PreparedStatementCallback%"),"PreparedStatementCallback",
    like(err_message,"Query definition missing%"),"Query definition missing",
    like(err_message,"Query is not allowed since data for sensitive column%"),"Query is not allowed since data for sensitive column",
    like(err_message,"Query result has errors while exporting the widget%"),"Query result has errors while exporting the widget",
    like(err_message,"QueryObject creation failed%"),"QueryObject creation failed",
    like(err_message,"Remote API error response could not be parsed%"),"Remote API error response could not be parsed",
    like(err_message,"Remote API response error%"),"Remote API response error",
    like(err_message,"REMOTE_API_RESPONSE_ERROR "),"REMOTE_API_RESPONSE_ERROR ",
    like(err_message,"Rest Client Exception Occurred%"),"Rest Client Exception Occurred",
    like(err_message,"SAP DBTech JDBC: Object is closed%"),"SAP DBTech JDBC: Object is closed",
    like(err_message,"SF API Returned error. Code: 4531%"),"SF API Returned error. Code: 4531 Failed to get metadata",
    like(err_message,"SFSF Metadata child node list is empty%"),"SFSF Metadata child node list is empty",
    like(err_message,"The parallel execution limit per tenant has been exceeded%"),"The parallel execution limit per tenant has been exceeded",
    like(err_message,"Unable to get data from publicAPI service"),"Unable to get data from publicAPI service",
    like(err_message,"Uncaught underlying exception%"),"Uncaught underlying exception",
    like(err_message,"Unexpected error occured%IOException: error 104 - Connection reset by peer%"),"Unexpected error occured IOException: error 104 - Connection reset by peer",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [139]: current operation cancelled by request and transaction rolled back"),"Unexpected error occured SAP DBTech JDBC: [139]: current operation cancelled by request and transaction rolled back",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [2]: general error: object name already exists%"),"Unexpected error occured SAP DBTech JDBC: [2]: general error",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [2048]: column store error%"),"Unexpected error occured SAP DBTech JDBC: [2048]: column store error",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [258]: insufficient privilege%"),"Unexpected error occured SAP DBTech JDBC: [258]: insufficient privilege",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [274]: inserted value too large for column%"),"Unexpected error occured SAP DBTech JDBC: [274]: inserted value too large for column",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [3]: fatal error%"),"Unexpected error occured SAP DBTech JDBC: [3]: fatal error",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [328]: invalid name of function or procedure%"),"Unexpected error occured SAP DBTech JDBC: [328]: invalid name of function or procedure",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [391]: invalidated view%"),"Unexpected error occured SAP DBTech JDBC: [391]: invalidated view",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: [4]: cannot allocate enough memory%"),"Unexpected error occured SAP DBTech JDBC: [4]: cannot allocate enough memory",
    like(err_message,"Unexpected error occured%SAP DBTech JDBC: Object is closed%"),"Unexpected error occured SAP DBTech JDBC: Object is closed",
    like(err_message,"Unexpected error occured%SQLNonTransientConnectionExceptionSapDB: Connection to database server lost%"),"Unexpected error occured SQLNonTransientConnectionExceptionSapDB: Connection to database server lost",
    like(err_message,"Unexpected error occured%SQLTransactionRollbackExceptionSapDB: [129]: transaction rolled back by an internal error%"),"Unexpected error occured SQLTransactionRollbackExceptionSapDB: [129]: transaction rolled back by an internal error",
    like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"Unexpected error occured DatabaseException Internal Exception",
    like(err_message,"Unexpected error occured: java.lang.ArrayIndexOutOfBoundsException%"),"Unexpected error occured: java.lang.ArrayIndexOutOfBoundsException",
    like(err_message,"Unexpected error occured: java.lang.IndexOutOfBoundsException%"),"Unexpected error occured: java.lang.IndexOutOfBoundsException",
    like(err_message,"Unexpected error occured: java.lang.NullPointerException%"),"Unexpected error occured: java.lang.NullPointerException",
    like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"Unexpected error occured DatabaseException Internal Exception",
    like(err_message,"Unexpected error occured%IOException: error 104 - Connection reset by peer"),"Unexpected error occured IOException: error 104 - Connection reset by peer",
    like(err_message,"Unexpected error occured%ResourceFailureException: PreparedStatementCallback%"),"Unexpected error occured ResourceFailureException: PreparedStatementCallback",
    like(err_message,"Unexpected error occured%UncategorizedSQLException: PreparedStatementCallback%"),"Unexpected error occured UncategorizedSQLException: PreparedStatementCallback",
    like(err_message,"Unexpected error occured%DatabaseException Internal Exception%"),"Unexpected error occured DatabaseException Internal Exception",
    like(err_message,"Unexpected error occured%TransactionSystemException: Could not commit JPA transaction%"),"Unexpected error occured%TransactionSystemException: Could not commit JPA transaction",
    like(err_message,"Unexpected error occured%HttpServerErrorException$$ServiceUnavailable: 503 Service Unavailable%"),"Unexpected error occured HttpServerErrorException$$ServiceUnavailable: 503 Service Unavailable",
    like(err_message,"Unexpected error occured%ResourceAccessException: I/O error on GET request%"),"Unexpected error occured ResourceAccessException: I/O error on GET request",
    like(err_message,"Unexpected error occured%UnknownHttpStatusCodeException: 555%"),"Unexpected error occured UnknownHttpStatusCodeException: 555",
    like(err_message,"Unexpected error occured%NestedServletException: Handler dispatch failed%"),"Unexpected error occured NestedServletException: Handler dispatch failed",
    like(err_message,"Unhandled error in servlet filter processing%"),"Unhandled error in servlet filter processing",
    like(err_message,"Unrecognized field \"isBaseDataSource\"%"),"Unrecognized field \"isBaseDataSource\"",
    like(err_message,"Unrecognized field \"sourceDataSourceIdFormated\"%"),"Unrecognized field \"sourceDataSourceIdFormated\"",
    like(err_message,"VCAP_SERVICES is valid JSON, but not a JSON object%"),"VCAP_SERVICES is valid JSON, but not a JSON object",
    like(err_message,"We failed to execute the query%"),"We failed to execute the query",
    like(err_message,"while trying to invoke the method com.sap.firefly.core.parameter.IPrElement.isStructure()%"),"while trying to invoke the method com.sap.firefly.core.parameter.IPrElement.isStructure()",
    like(err_message,"while trying to invoke the method com.sap.firefly.olap.manager.IQueryManager.setMaxResultRecords(long)%"),"while trying to invoke the method com.sap.firefly.olap.manager.IQueryManager.setMaxResultRecords(long)",
    like(err_message,"while trying to invoke the method java.sql.Timestamp.compareTo(java.sql.Timestamp)%"),"while trying to invoke the method java.sql.Timestamp.compareTo(java.sql.Timestamp)",
    like(err_message,"while trying to invoke the method liquibase.logging.LogService.getLog(java.lang.Class)%"),"while trying to invoke the method liquibase.logging.LogService.getLog(java.lang.Class)",
    like(err_message,"Index:%, Size:%"),"Index:..., Size:",
    like(err_message,"null"),"null",
    like(err_message,"Unexpected error occured%IOException: error 32 - Broken pipe"),"Unexpected error occured IOException: error 32 - Broken pipe",
    like(err_message,"SAP DBTech JDBC: [597]: session context error%"),"SAP DBTech JDBC: [597]: session context error",
    like(err_message,"%Unexpected error occurred%IOException: error 32 - Broken pipe"),"Unexpected error occurred IOException: error 32 - Broken pipe",
    like(err_message,"504 Gateway Time-out%"),"504 Gateway Time-out",
    like(err_message,"ERROR_CODE 42522 No values set for mandatory variable%"),"ERROR_CODE 42522 No values set for mandatory variable",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [597]: session context error%"),"Unexpected error occurred SAP DBTech JDBC: [597]: session context error",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [601]: too many session variables are set%"),"Unexpected error occurred SAP DBTech JDBC: [601]: too many session variables are set",
    like(err_message,"Unexpected error occurred%IOException: error 110 - Connection timed out%"),"Unexpected error occurred IOException: error 110 - Connection timed out",
    like(err_message,"%Unexpected error occurred%IOException: error 32 - Broken pipe"),"Unexpected error occurred IOException: error 32 - Broken pipe",
    like(err_message,"401 : \"Wrapper token invalid\""),"401 : \"Wrapper token invalid\"",
    like(err_message,"500 : \"Internal server error%"),"500 : \"Internal server error",
    like(err_message,"504 Gateway Time-out"),"504 Gateway Time-out",
    like(err_message,"Data receive failed%error 104 - Connection reset by peer%"),"Data receive failed error 104 - Connection reset by peer",
    like(err_message,"Error occured during initial fetching x509 certificate  for vault"),"Error occured during initial fetching x509 certificate  for vault",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42017: Not authorized%"),"ERROR_CODE 42014 Caught exception : exception 42017: Not authorized",
    like(err_message,"ERROR_CODE 42014 Caught exception : exception 42248: A cube operation failed%"),"ERROR_CODE 42014 Caught exception : exception 42248: A cube operation failed",
    like(err_message,"ERROR_CODE 42024 An expected attribute is missing%"),"ERROR_CODE 42024 An expected attribute is missing",
    like(err_message,"ERROR_CODE 42432 Dimension attribute referenced in view is not defined%"),"ERROR_CODE 42432 Dimension attribute referenced in view is not defined",
    like(err_message,"ERROR_CODE 42522 No values set for mandatory variable"),"ERROR_CODE 42522 No values set for mandatory variable",
    like(err_message,"ERROR-5008 Fields are empty in QueryScenarioDataSource%"),"ERROR-5008 Fields are empty in QueryScenarioDataSource",
    like(err_message,"Fail to get MDS heart beat information%"),"Fail to get MDS heart beat information",
    like(err_message,"Liquibase process failed due to incompatible column datatypes%"),"Liquibase process failed due to incompatible column datatypes",
    like(err_message,"%JDBCDriverException: SAP DBTech JDBC: [600]: failed routed execution%"),"JDBCDriverException: SAP DBTech JDBC: [600]: failed routed execution",
    like(err_message,"%JDBCDriverException: SAP DBTech JDBC: Object is closed%"),"JDBCDriverException: SAP DBTech JDBC: Object is closed",
    like(err_message,"SAP DBTech JDBC: [2566]: distributed environment error%"),"SAP DBTech JDBC: [2566]: distributed environment error",
    like(err_message,"SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel%"),"SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel",
    like(err_message,"SAP DBTech JDBC: [2567]: network error: the application threw an exception%"),"SAP DBTech JDBC: [2567]: network error: the application threw an exception",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [145]: transaction distribution work failure%"),"Unexpected error occurred SAP DBTech JDBC: [145]: transaction distribution work failure",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2566]: distributed environment error%"),"Unexpected error occurred SAP DBTech JDBC: [2566]: distributed environment error",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel"),"Unexpected error occurred SAP DBTech JDBC: [2567]: network error: an error occured while opening the channel",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [2567]: network error: the application threw an exception"),"Unexpected error occurred SAP DBTech JDBC: [2567]: network error: the application threw an exception",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure%"),"Unexpected error occurred SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure",
    like(err_message,"Unexpected error occurred%SAP DBTech JDBC: [601]: too many session variables are set%"),"Unexpected error occurred SAP DBTech JDBC: [601]: too many session variables are set",
    like(err_message,"Unexpected error occurred%URLDecoder: Illegal hex characters%"),"Unexpected error occurredURLDecoder: Illegal hex characters",
    like(err_message,"Unexpected error occurred%URLDecoder: Incomplete trailing escape%"),"Unexpected error occurred URLDecoder: Incomplete trailing escape",
    like(err_message,"Unexpected error occurred%Timeout: Pool empty. Unable to fetch a connection%"),"Unexpected error occurred Timeout: Pool empty. Unable to fetch a connection",

    like(err_message,"%404 Not Found:%"),"404 Not Found:",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 1000002: message not found;Allocation failed%"),"ERROR_CODE 42014 Caught exception : exception 1000002: message not found;Allocation failed",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 42219: The Source queries cannot be blended : Query name not found in DataSource definition:%"),"ERROR_CODE 42014 Caught exception : exception 42219: The Source queries cannot be blended : Query name not found in DataSource definition:",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 42556: Extended dimension processing error : Can't read view%"),"ERROR_CODE 42014 Caught exception : exception 42556: Extended dimension processing error : Can't read view",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 70000129: transaction rolled back by an internal error: Allocation failed %"),"ERROR_CODE 42014 Caught exception : exception 70000129: transaction rolled back by an internal error: Allocation failed ",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 70006930: attribute value is not a number;attribute value is not a number;exception 70006930: attribute value is not a number%"),"ERROR_CODE 42014 Caught exception : exception 70006930: attribute value is not a number;attribute value is not a number;exception 70006930: attribute value is not a number",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 70034011: Inconsistent calculation model;calculationNode%"),"ERROR_CODE 42014 Caught exception : exception 70034011: Inconsistent calculation model;calculationNode",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 71000591: SQLException exception 1000002: Allocation failed%"),"ERROR_CODE 42014 Caught exception : exception 71000591: SQLException exception 1000002: Allocation failed",
    like(err_message,"%ERROR_CODE 42018 Internal error occurred while processing : Can't find source cube%"),"ERROR_CODE 42018 Internal error occurred while processing : Can't find source cube",
    like(err_message,"%ERROR_CODE 42018 Internal error occurred while processing:  : Cube for totals not found%"),"ERROR_CODE 42018 Internal error occurred while processing:  : Cube for totals not found",
    like(err_message,"%ERROR_CODE 42203 Measure not found%"),"ERROR_CODE 42203 Measure not found",
    like(err_message,"%ERROR_CODE 42209 Base measure does not exist in view : Invalid self reference or reference%"),"ERROR_CODE 42209 Base measure does not exist in view : Invalid self reference or reference",
    like(err_message,"%Failed export for story%"),"Failed export for story",
    like(err_message,"%Failed to post story job completion status to DB%"),"Failed to post story job completion status to DB",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [459]: invalidated function%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [459]: invalidated function",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [601]: too many session variables are set%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [601]: too many session variables are set",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: Cannot connect to jdbc%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: Cannot connect to jdbc",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.SQLNonTransientConnectionExceptionSapDB: Data receive failed%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.SQLNonTransientConnectionExceptionSapDB: Data receive failed",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.SQLNonTransientConnectionExceptionSapDB: Invalid packet%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.SQLNonTransientConnectionExceptionSapDB: Invalid packet",
    like(err_message,"%Unexpected error occured: org.apache.tomcat.jdbc.pool.PoolExhaustedException%"),"Unexpected error occured: org.apache.tomcat.jdbc.pool.PoolExhaustedException",
    like(err_message,"%Unexpected error occured: org.springframework.beans.factory.BeanCreationException%"),"Unexpected error occured: org.springframework.beans.factory.BeanCreationException",
    like(err_message,"%Unexpected error occured: org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Unavailable%"),"Unexpected error occured: org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Unavailable",
    like(err_message,"%Unexpected error occured: org.springframework.web.client.ResourceAccessException: I/O error on DELETE%"),"Unexpected error occured: org.springframework.web.client.ResourceAccessException: I/O error on DELETE",

    like(err_message,"%Could not commit JPA transaction; nested exception is javax.persistence.RollbackException%"),"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException",
    like(err_message,"%ERROR_CODE 42014 Caught exception : exception 70006944: AttributeEngine: overflow in numeric calculation%"),"ERROR_CODE 42014 Caught exception : exception 70006944: AttributeEngine: overflow in numeric calculation",
    like(err_message,"%ERROR_CODE 42554 Invalid custom member : Formula member  uses the not existing member%"),"ERROR_CODE 42554 Invalid custom member : Formula member  uses the not existing member",
    like(err_message,"QueryObject creation failed for:%"),"QueryObject creation failed",
    like(err_message,"%Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure%"),"Unexpected error occured: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [329]: cannot use duplicate name of function or procedure",
    like(err_message,"%Unexpected error occured: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape%"),"Unexpected error occured: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape",
    like(err_message,"%ERROR_CODE 42421 The aggregation dimension does not exist in the view%"),"ERROR_CODE 42421 The aggregation dimension does not exist in the view",
    like(err_message,"%Missing context field%in Query Model:%"),"Missing context field ... in Query Model",

    like(err_message,"%ERROR-5017 Target Field%does not exists%"),"ERROR-5017 Target Field ... does not exists",
    like(err_message,"%while trying to invoke the method%of a null object%"),"while trying to invoke the method ... of a null object",
    like(err_message,"%System cannot be resolved:%"),"System cannot be resolved",

    like(err_message,"%%"),"Blank",
    1==1,err_message)

| eval errorType=case(
    like(_raw, "%The parallel execution limit per tenant has been exceeded:100%"), "Failed to execute query (Execution limit exceeded)", 
    like(_raw, "%Error occured while saving labels to DB%"), "Save Labels Error", 
    like(_raw, "%User authentication validation failed due to invalid authentication details.%"), "Invalid Authentication", 
    like(_raw, "%Error retrieving translations from remote API%"), "Remote API Error", 
    like(_raw, "%HDI Deployment active: false%"), "HDI Deployment", 
    like(_raw, "%Request: /qbuilder/sap/fpa/remote/qbuilder/GetServerInfo Unable to parse%"), "Parse Error", 
    like(_raw, "%does not have the correct naming convention!%"), "Package Naming", 
    like(_raw, "%Error occured while extracting story execution details from Ina request.%"), "Execution Details Extraction", 
    like(_raw, "%Language is not set in the inaRequest%"), "Language Not Set", 
    like(_raw, "%Unhandled error in servlet filter processing.%"), "Unhandled Error", 
    like(_raw, "%Token decryption failed.%"), "Token Decryption", 
    like(_raw, "%Unexpected error occured: com.sap.orca.remote.qbuilder.rest.exceptions.ServerErrorException%"), "Unexpected error occurred", 
    like(_raw, "%I/O error on POST request for%"), "I/O Error", 
    like(_raw, "%GenericRemoteAPI call failed. Request URI:%"), "GenericRemoteAPI call failed", 
    like(_raw, "%403 Forbidden%"), "403 Forbidden", like(_raw, "%500 Internal Server Error:%"), "500 Internal Server Error", 
    like(_raw, "%Query is not activated and will be deleted%"), "Query is not activated", 
    like(_raw, "%Package name missing%"), "Package name missing", 
    like(_raw, "%Could not commit JPA transaction%"), "JPA Transaction Commit", 
    like(_raw, "%com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC%"), "JDBCDriverException", 
    like(_raw, "%ERROR_CODE5037\"Column does not exist in calculation View\"%"), "Column does not exist", 
    like(_raw, "%does not exists in data source%"), "Data source", 
    like(_raw, "%Unexpected error occured: org.apache.catalina.connector.ClientAbortException: java.net.SocketTimeoutException%"), "Socket Timeout", 
    like(_raw, "%Unexpected error occured: java.lang.NullPointerException%"), "NullPointer", 
    like(_raw, "%Cannot forward to error page for request%"), "Error Page forwarding", 
    like(_raw, "%Unexpected error occured: java.util.MissingResourceException%"), "MissingResourceException", 
    like(_raw, "%Unexpected error occured: org.springframework.beans.factory.BeanCreationException:%"), "BeanCreationException", 
    like(_raw, "%Rest Client Exception Occurred : org.springframework.web.client.ResourceAccessException%"), "ResourceAccessException", 
    like(_raw, "%SFSF Metadata child node list is empty.%"), "Child Node empty", 
    like(_raw, "%User authentication service call failed%"), "User Authentication Service Failure", 
    like(_raw, "%Remote API error: Invalid node Id or error while fetching label%"), "Invalid Node Id", 
    like(_raw, "%406 Not Acceptable%"), "406 Not Acceptable", 
    like(_raw, "%java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xerces.internal.impl.msg.XMLSchemaMessages%"), "Could not load any resource bundle", 
    like(_raw, "%LogicalModelName is null/empty in logical model%"), "Logical Model Null", 
    like(_raw, "%c.s.o.r.q.o.s.q.RuntimeMetadataHandler%"), "RuntimeMetadataHandler", 
    like(_raw, "%PooledConnection has already been closed.%"), "PooledConnection has already been closed", 
    like(_raw, "%File not found:%"), "File not found", 
    like(_raw, "%Failed to get the server information:%"), "Failed to get the server information", 
    like(_raw, "%ERROR-5018: Source data source%"), "ERROR-5018: Source data source", 
    like(_raw, "%Unexpected error occured: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe%"), "IOException: Broken pipe", 
    like(_raw, "%VCAP_SERVICES is valid JSON, but not a JSON object%"), "VCAP_SERVICES not a valid JSON", 
    like(_raw, "%504 Gateway Time-out%"), "504 Gateway Time-out", 
    like(_raw, "%Unexpected error occured: com.sap.db.jdbc.exceptions.InternalReconnectException%"), "InternalReconnectException", 
    like(_raw, "%ERROR-5008:%"), "ERROR-5008", like(_raw, "%Translations: NodeSource information not available for%"), "Translations- NodeSource information not available", 
    like(_raw, "%Unable to parse the Accept-Language: en-US,en;q=0.9%"), "Language Parse Error", 
    like(_raw, "%Right datasource rd5 is used in two joins%"), "Data source join", 
    like(_raw, "%ERROR-5028:%"), "ERROR-5028", 
    like(_raw, "%Unexpected error occured: java.lang.ArrayIndexOutOfBoundsException%"), "ArrayIndexOutOfBoundsException", 
    like(_raw, "%Could not extract response%"), "Could not extract response", 
    like(_raw, "%com.sap.db.jdbc.ConnectionSapDB._tryReconnect%"), "ConnectionSapDB._tryReconnect", 
    like(_raw, "%502 Bad Gateway:%"), "502 Bad Gateway:", 
    like(_raw, "%401 Bad credentials%"), "401 Bad credentials", 
    like(_raw, "%Ljava.lang.StackTraceElement%"), "StackTraceElement", 
    like(_raw, "%Unexpected error occured: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException%"), "MalformedJsonException", 
    like(_raw, "%Query not found.%"), "Query not found", 
    like(_raw, "%Error Fetching and Building widget List: A server error has occurred%"), "Building widget List", 
    like(_raw, "%Unable to get data from publicAPI service%"), "Public API Error", 
    like(_raw, "%Exception while processing variables%"), "Exception while processing variables", 
    like(_raw, "%Error during processSynchronization.%"), "Error during processSynchronization", 
    like(_raw, "%The selection returned more records than the limit in MaxResultRecords%"), "The selection returned more records than the limit ", 
    like(_raw, "%Unexpected error occured: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer%"), "IOException: Connection reset by peer", 
    like(_raw, "%QueryObject creation failed for:%"), "QueryObject creation failed", 
    like(_raw, "%java.sql.SQLException: Connection has already been closed.%"), "SQLException: Connection has already been closed", 
    like(_raw, "%Unexpected error occured: org.springframework.orm.jpa.JpaSystemException:%"), "JpaSystemException", 
    like(_raw, "%SAP DBTech JDBC: [258]: insufficient privilege:%"), "insufficient privilege", 
    like(_raw, "%Error while writing csv export response to DB%"), "Error writing csv export response", 
    like(_raw, "%Unexpected error occured: org.springframework.web.client.ResourceAccessException:%"), "Unexpected error occured: ResourceAccessException", 
    like(_raw, "%Failed to execute an InA query:%"), "Failed to execute an InA query", 
    like(_raw, "%Empty root node list.%"), "Empty root node list", 
    1==1, "Unknown Error")

| eval date = strftime(_time, "%Y-%m-%d") 
| eval weekday = strftime(_time, "%A") 
| eval time = strftime(_time, "%H:%M") 
| eval hour = "\"" + substr(time,1,2) + "\""
| eval minute = strftime(_time, "%M")
| eval time_2 = strftime(_time + if(minute%2=0,0,(2-minute%2)*60), "%H:%M")
| eval time_3 = strftime(_time + if(minute%3=0,0,(3-minute%3)*60), "%H:%M")
| eval date_2 = strftime(_time + if(time="23:59",86400,0), "%Y-%m-%d")
| eval date_3 = strftime(_time + if(time="23:58" OR time="23:59",86400,0), "%Y-%m-%d") | fields - minute
| eval server = if(servername!="", servername, host)
| eval server_type = if (substr(server, 1, 2) = "pc", "PROD", if (substr(server, 1, 2) = "sc", "PREVIEW", if (substr(server, 1, 2) = "ac", "QA",if (substr(server, 1, 2) = "ps", "SALES DEMO", "OTHER") ) ) ) 
| eval sac_app_correlation_id=replace(sac_app_correlation_id, "\-" , "")

| eval skip=substr(skip, 1, 256) | eval err_message=substr(err_message, 1, 256)

| eval id=1 | accum id | eval count=1

| rename SFDC AS "dc", sac_app_company_id as "instance", sac_app_correlation_id as "correl", component as errorClass, err_message as errorCategory

| eval tempTime = strftime(_time, "%H:%M:%S") | dedup instance, date, tempTime, correl | fields - tempTime

| table id, date, weekday, time, hour, dc, sourcetype, server, server_type, instance, correl, errorClass, errorCategory, errorType, count, time_2, date_2, time_3, date_3
